version: "3.8"

services:
  api:
    container_name: "howsfit"

    build: ./
    restart: always

    ports:
      - "8000:8000"
    volumes:
      - .:/app
    shm_size: 3GB
    command:
      - nvidia-smi
      - uvicorn main:app --reload --host 0.0.0.0 --port 8000
    networks:
      - local-net


networks:
  local-net:
    driver: bridge